# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: MegaMekLab CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci_cd:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew (*nix or MacOS)
      run: chmod +x gradlew
    - name: Checkout MegaMek
      uses: actions/checkout@v2
      with:
        repository: MegaMek/megamek
        path: ./megamek
    - name: Build settings_local.gradle and properties_local.gradle
      run: |
        echo "includeBuild './megamek'" >settings_local.gradle
        echo "rootProject.ext.mmDir = './megamek'" >properties_local.gradle
    - name: Build with Gradle
      id: gradle_build
      run: ./gradlew -I .github/build-scan-init.gradle build --stacktrace --scan "-Dscan.link.VCS=${{ github.event.pull_request.html_url }}"
    - name: Upload Test Logs on Failure
      uses: actions/upload-artifact@v2-preview
      if: failure()
      with:
        name: cd-failure-logs
        path: build/reports/
    - name: Comment on PR with Build Scan URI
      uses: thollander/actions-comment-pull-request@master
      with:
        message: Build scan available at ${{ steps.gradle_build.outputs.buildScanUri }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload Releases
      uses: actions/upload-artifact@v2-preview
      with:
        name: releases
        path: build/distributions/
  other_os_ci:
    runs-on: ${{ matrix.os }}
    needs: ci_cd
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew (*nix or MacOS)
      run: chmod +x gradlew
      if: runner.os != 'Windows'
    - name: Checkout MegaMek
      uses: actions/checkout@v2
      with:
        repository: MegaMek/megamek
        path: ./megamek
    - name: Build settings_local.gradle and properties_local.gradle
      run: |
        echo "includeBuild './megamek'" >settings_local.gradle
        echo "rootProject.ext.mmDir = './megamek'" >properties_local.gradle
    - name: Test with Gradle
      run: ./gradlew test --stacktrace
    - name: Upload Test Logs on Failure
      uses: actions/upload-artifact@v2-preview
      if: failure()
      with:
        name: ci-failure-logs
        path: build/reports/
